# Example Configuration File for Your Experiment

seed: 42
log_dir: 'logs'

dataset:
  name: 'financial'
  file: 'loan'
  column: 'status'
  task: 'classification'

train:
  mode: 'standard'
  epoch: 200
  patience: 50

model:
  type: 'GNN'
  subtype : 'GCN'
  input_dim : 38
  output_dim : 4
  hidden_dim : 16
  layer : 2
  head : 2 # Only some models will utilise this argument.

optim:
  optimizer: 'adam'
  lr: 0.01
  scheduler: 'cos'
