# Example Configuration File for Your Experiment

seed: 42
log_dir: 'logs'

dataset:
  name: 'rdb3-lahman'
  file: 'managers'
  column: 'RankTeam'
  type: 'graph'

train:
  mode: 'standard'
  epoch: 200
  patience: 5

model:
  type: 'GNN'
  subtype: 'GCN'
  hidden_dim: 16
  layer: 2
  head: 4

optim:
  optimizer: 'adam'
  lr: 0.001
  weight_decay: 0
  scheduler: 'cos'
  # for step scheduler
  milestones: [9,16]
  lr_decay: 0.1
  # for SGD optimizer
  momentum: 0.9
