# Example Configuration File for Your Experiment

seed: 42
log_dir: 'logs'

dataset:
  name: 'financial'
  file: 'loan'
  column: 'status'
  task: 'classification'

train:
  mode: 'standard'
  epoch: 20
  patience: 5

model:
  type: 'HGNN'
  subtype : 'HGT'
  input_dim : 21
  output_dim : 4
  hidden_dim : 24
  layer : 2
  head : 2 # Only some models will utilise this argument.

optim:
  optimizer: 'adam'
  lr: 0.01
  weight_decay: 0.0005
  scheduler: 'cos'

  max_epoch: 20
  # for step scheduler
  milestones: [9,16]
  lr_decay: 0.1
  # for SGD optimizer
  momentum: 0.9
