# Example Configuration File for Your Experiment

seed: 42
log_dir: 'logs'

dataset:
  data_dir: "Datasets/"
  name: 'rdb1-seznam'
  file: 'charge'
  column: 'ChargeService'
  type: 'single'
  url: 'https://github.com/YiYang-github/RDBench-Dataset/archive/refs/heads/master.zip'

train:
  mode: 'standard'
  epoch: 200

model:
  type: 'ResNet'
  subtype: ''
  hidden_dim: 128
  layer: 4
  head: 4

optim:
  optimizer: 'adam'
  lr: 0.001
  weight_decay: 0
  scheduler: 'cos'
  # for step scheduler
  milestones: [9,16]
  lr_decay: 0.1
  # for SGD optimizer
  momentum: 0.9
