# Example Configuration File for Your Experiment

seed: 42
log_dir: 'logs'

dataset:
  # name: 'rdb3-toxic'
  # file: 'bond_count'
  # column: 'Count'
  # task: 'classification'
  # file: 'atom'
  # column: 'Arg4'
  # task: 'regression'
  type: 'graph'
  name: 'example'
  file: 'loan'
  column: 'Status'
  task: 'classification'
  type: 'single'

train:
  mode: 'standard'
  epoch: 200
  patience: 5

model:
  type: 'MLP'
  subtype: 'GCN'
  hidden_dim: 128
  layer: 4
  head: 4

optim:
  optimizer: 'adam'
  lr: 0.001
  weight_decay: 0
  scheduler: 'cos'
  # for step scheduler
  milestones: [9,16]
  lr_decay: 0.1
  # for SGD optimizer
  momentum: 0.9
