site_name:  DBGym Docs

theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - toc.integrate 
    - navigation.top
    - navigation.indexes

plugins:
  - mkdocstrings

nav:
  - Overview: index.md
  - Get started: start.md
  - Tutorials: tutorials.md
  - Package reference:
    # - intro_index.md 
    - dbgym.model :   reference/model.md
    - dbgym.dataset: reference/dataset.md
    - dbgym.db:    reference/db.md
    - dbgym.db2graph: reference/db2graph.md
    - dbgym.optimizer:  reference/optimizer.md
    - dbgym.train:   reference/train.md
    - dbgym.loss:    reference/loss.md
    - dbgym.config:  reference/config.md
    - dbgym.logger:  reference/logger.md
    - dbgym.register: reference/register.md

  - External resources: external.md
