[build-system]
requires = ['hatchling']
build-backend = "hatchling.build"

[project]
name = "dbgym"
version = "0.1.3"
authors = [
  { name="DBGym Team", email="jiaxuan@cs.stanford.edu" },
]
description = "DBGym: platform for relational database benchmark RDBench"
readme = "README.md"
license='MIT'
classifiers = [
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.10"
dependencies = [
    'matplotlib',
    'numpy',
    'pandas',
    'scikit_learn',
    'torch',
    'torch_geometric',
    'xgboost',
    'yacs',
    'requests'
]

[project.urls]
"Homepage" = "https://github.com/JiaxuanYou/DBGym"
"Bug Tracker" = "https://github.com/JiaxuanYou/DBGym/issues"
