# Example Configuration File for GCN

seed: 42
log_dir: output
device: auto

dataset:
  dir: ./Datasets/
  name: rdb2-bank
  query: loan.Status
  type: graph

train:
  epoch: 200

model:
  name: GCN
  hidden_dim: 128
  layer: 4

optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.0001
  scheduler: cos
